language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: YyCm6ciFOt058+jfcNJtOvUfJEKYM3rilNr/Xx0nwVG6RVRVdlkq9poqEQ3H7Pwmgpwdp87UHyOgPEQ6PDMkYTmXfYSF4jI9CPAqL50760th1mU6BVahiGxfGq1RFHaTGZ/r2LomlUj/18p537TFreVu9QzgkMhtkdKFxsgDSKocqZckkQnCORDIPPKwQO0zKnsUZBaLVFgoc4c4kqfxxlqKmW7HR50ORvNS4+QC3KN03zBziz47kuIjEYY0VayKHwGgaNcb1QXI4CIuLh10XSX9nuNFTYoQmYit0r5AFI93lnHMgyEE9PgfpZlI65fjBT7U7ES37zx13uWk/1ph/cyZA+ViE/mqkgZaz+ujpgXQep2NzMJmAQwoCbzN3AG5TmzhY2Pe3atvpQecSq1Tglx03WPX5kt5Uuuj6jT7Zanmo1hEyURLQxGIfzm00OOod8Y5fSoW5pDgK9hS4cA6BvFEZ6uqHpwt+a28l+3S0TYKBMmgmI6w0VGrB70nvVjq7SwUlF/wrMB1o3OfqR7pp78cK63Yh293Mzl6/WxMntkafbX3Yf3XkXtx/BhNIeSzmfMZjlloIhGMBwy088lcFy9uH+SIhTeXu7PsMwDpQ5J5851rYtR+fTUsAGKScQWrrJ6IzLCH/XvK2p37cM+l5sl9LoKp9tr9z2UUPPxn9ZA=
  app: com-ryanlabouve-blog
  on:
    repo: ryanlabouve/com-ryanlabouve-blog
